In [1]:
import numpy as np

In [2]:
Z = np.zeros(7)

In [4]:
Z

array([0., 0., 0., 0., 0., 0., 0.])

In [5]:
ar=np.array([1,2,3])
ar

array([1, 2, 3])

In [6]:
ran=np.random.rand(4)
ran

array([0.47758168, 0.68332543, 0.59621913, 0.49646718])

In [7]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [8]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2 = np.array([1,2,3,4,5], dtype=np.int16)

In [10]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [11]:
ar2=np.array([[1,2,3],[4,5,6]])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
z1=np.zeros((5,5))
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
o1=np.ones((5,5))
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
r1=np.random.rand(4,5)
r1

array([[0.04384005, 0.02364111, 0.52234089, 0.21454208, 0.69273235],
       [0.15350245, 0.84839735, 0.22291557, 0.89051514, 0.80781612],
       [0.87755687, 0.73575213, 0.10965749, 0.32824247, 0.98682987],
       [0.27425999, 0.37998691, 0.4542121 , 0.33925171, 0.93412927]])

In [16]:
import numpy as np # Import the NumPy library and give it the alias 'np'

ar = np.array([0,1,2,3,4,5,6,7,8,9]) # Use np.array to create NumPy arrays
ar2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
print(ar2.size)

9


In [17]:
print(ar2.shape)

(3, 3)


In [18]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
ar3[1,2]=12
ar3[0,1]=15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [20]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [21]:
ar3=np.sort(ar3,axis=0)
ar3

array([[ 1,  3,  9],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [22]:
ar3.sum()

np.int64(64)

In [23]:
ar3.sum(axis=0)

array([12, 16, 36])

In [24]:
ar4=np.random.rand(99)

In [26]:
ar4.size

99

In [27]:
ar4=ar4.reshape(11,9)

In [28]:
ar4.shape

(11, 9)

In [29]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [ 9, 12, 15]])

In [30]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
ar=np.delete(ar,6,axis=0)

In [33]:
ar

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [34]:
ar=np.insert(ar,6,6)

In [35]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [ 9, 12, 15]])

In [38]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [ 9, 12, 15]])

In [39]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9,  9, 12, 15]])

In [40]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [ 9, 12, 15]])]

In [41]:
ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
ar6[1]

array([[7, 8, 9],
       [1, 4, 7]])

In [43]:
ar6[2]

array([[ 3,  5,  8],
       [ 9, 12, 15]])

In [44]:
ar6[0][0][0]

np.int64(1)

In [45]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 10, 13, 16]])

In [46]:
np.subtract(ar5,1)

array([[ 0,  1,  2,  0,  3,  6],
       [ 3,  4,  5,  2,  4,  7],
       [ 6,  7,  8,  8, 11, 14]])

In [47]:
np.multiply(ar5,1)

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9,  9, 12, 15]])

In [48]:
np.power(ar5,1)

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9,  9, 12, 15]])

In [49]:
np.power(ar5,2)

array([[  1,   4,   9,   1,  16,  49],
       [ 16,  25,  36,   9,  25,  64],
       [ 49,  64,  81,  81, 144, 225]])

In [50]:
ar7=np.add(ar6[0],ar6[1])
print(ar7)

[[ 8 10 12]
 [ 5  9 13]]


In [51]:
ar8=np.multiply(ar6[0],ar6[1])
print(ar8)

[[ 7 16 27]
 [ 4 20 42]]


In [52]:
ar9=np.divide(ar6[0],ar6[1])
print(ar9)

[[0.14285714 0.25       0.33333333]
 [4.         1.25       0.85714286]]


In [53]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [54]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [55]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

In [56]:
np.mean(ar5)

np.float64(6.055555555555555)

In [57]:
np.median(ar5)

np.float64(5.5)

In [58]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.        ])

In [60]:
np.median(ar5,axis=1)

array([2.5, 5. , 9. ])

In [61]:
np.min(ar5)

np.int64(1)

In [62]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [63]:
np.max(ar5,axis=0)

array([ 7,  8,  9,  9, 12, 15])

In [68]:
ar10=np.array([1,2,3,4,5,6,7,8,9])
ar10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.argmax(ar)

np.int64(9)

In [70]:
np.argmin(ar)

np.int64(0)

In [71]:
np.argsort(ar10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
np.sin(ar10)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
np.log(ar10)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [74]:
ar11 = np.array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [75]:
np.mean(ar11)

np.float64(86.66666666666667)

In [76]:
np.median(ar11)

np.float64(88.0)

In [77]:
np.min(ar11)

np.int64(76)

In [78]:
np.max(ar11)

np.int64(95)

In [79]:
ar11=ar11.reshape(2,9)
ar11

array([[85, 90, 78, 92, 88, 95, 76, 95, 85],
       [76, 95, 85, 90, 85, 92, 88, 76, 89]])

In [80]:
ar11 = np.array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [82]:
ar11.sort()
ar11

array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

In [83]:
np.sin(ar10)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [84]:
np.log(ar10)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])